package enums;

public enum AdminButt {
	CLOSE,DOCTOR_ADD,NURSE_ADD,DOCTOR_LIST,NURSE_LIST,FIND_BY_DOC_ID,FIND_BY_NUR_ID,
	FIND_BY_DOC_NAME,FIND_BY_NUR_NAME,CHANGE_DOC_INFO,CHANGE_NUR_INFO,DELETE_DOC,DELETE_NUR;
}
